### ISSUE TITLE
Feature: Werkt allemaal nie

### ISSUE THREAD

**Issue by LuukEbenau** [metalglove/Kwetter#42]
### Description
As a (role), I'd like to (feature short description), in order to (value it adds).

### Acceptance Criteria
Reference: Done-Done Checklist
- [ ] Should (testable condition that should be satisfied)
- [ ] Should (testable condition that should be satisfied)
- [ ] Should (testable condition that should be satisfied)

Also, here are a few points that need to be addressed:

1. Constraint 1:

### Tasks
- [x] _TBA_
- [x] _TBA_
- [x] _TBA_

**Comment by metalglove** [comment]
welles
